version: "3.9"
services:
  api:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      environment:
        - DB_SOURCE=postgresql://citus:D1git4l@2024@c-db-postgresql-cluster.tkfmrksaxftprl.postgres.cosmos.azure.com:5432/pocdigital
      entrypoint: ["/app/start.sh"]
      command: ["/app/main"]